export {
  AUDIENCES,
  CORE_TERM_COUNT,
  DEFAULT_AUDIENCE,
  PRESETS,
  isAudience,
  parseAudience,
  presetOf,
  type AnalogyRule,
  type Audience,
  type AudiencePreset,
  type Band,
  type CoverageRule,
  type Register,
} from './audience.js';
export {
  EVIDENCE_WORDS,
  MIN_CONTENT_WORDS,
  contentWords,
  groundingOf,
  type Grounding,
} from './grounding.js';
export {
  coreTerms,
  extractTerms,
  findTermUses,
  sentenceSpans,
  type Span,
  type ExtractResult,
  type Term,
  type TermKind,
  type TermUse,
} from './terms.js';
export {
  DETERMINISTIC_AXES,
  EXIT_CODE,
  MAX_ATTEMPTS,
  decide,
  formatExplainReport,
  judgeAccuracy,
  registerStats,
  runExplainCheck,
  withAxis,
  type AxisResult,
  type Decision,
  type ExplainAxis,
  type ExplainCheckOptions,
  type ExplainMetrics,
  type ExplainReport,
  type JudgeInput,
  type NextAction,
  type RegisterStats,
  type Verdict,
} from './check.js';
