export {
  parseRuleBook,
  parseRegister,
  ruleLabel,
  s1Ids,
  type RuleScanOptions,
  citedRuleIds,
  expandIdRanges,
  QUICK_RULES_PATH,
  type Register,
  type Rule,
  type RuleBook,
  type Severity,
} from './rules.js';
export {
  detect,
  countByRule,
  protectedTokens,
  missingProtectedTokens,
  structureStats,
  splitSentences,
  reportRegisterStats,
  spacingIssues,
  DETECTABLE_RULE_IDS,
  type Detection,
  type ReportRegisterStats,
  type SpacingIssue,
  type StructureStats,
} from './detectors.js';
export { changeRate, type ChangeRateOptions } from './change-rate.js';
export {
  runCheck,
  prescan,
  decide,
  formatReport,
  EXIT_CODE,
  THRESHOLD,
  MAX_ATTEMPTS,
  type CheckReport,
  type PrescanReport,
  type Decision,
  type NextAction,
  type RunCheckOptions,
  type RunCheckWithPrescan,
  type AxisResult,
  type Verdict,
} from './check.js';
export { scan, formatScan, type ScanReport, type ScanHit, type ScanOptions } from './scan.js';
