import { z } from 'zod';

// ─── Interview Tool ─────────────────────────────────────────────
export const interviewInputSchema = z.object({
  action: z.enum(['start', 'respond', 'score', 'complete']),
  topic: z.string().optional(),
  sessionId: z.string().optional(),
  response: z.string().optional(),
  cwd: z.string().optional(),
  generatedQuestion: z.string().optional()
    .describe('Question generated by the caller LLM (passthrough mode)'),
  ambiguityScore: z.object({
    goalClarity: z.number().min(0).max(1),
    constraintClarity: z.number().min(0).max(1),
    successCriteria: z.number().min(0).max(1),
    priorityClarity: z.number().min(0).max(1),
    contextClarity: z.number().min(0).max(1).optional(),
    contradictions: z.array(z.string()).optional(),
  }).optional().describe('Ambiguity scores computed by the caller LLM (passthrough mode)'),
});

export type InterviewInput = z.infer<typeof interviewInputSchema>;

// ─── Spec Tool ──────────────────────────────────────────────────
export const specInputSchema = z.object({
  sessionId: z.string(),
  force: z.boolean().optional().default(false),
  spec: z.object({
    goal: z.string(),
    constraints: z.array(z.string()),
    acceptanceCriteria: z.array(z.string()),
    ontologySchema: z.object({ entities: z.array(z.any()), relations: z.array(z.any()) }),
    gestaltAnalysis: z.array(z.any()),
  }).optional().describe('Externally generated spec (passthrough mode)'),
});

export type SpecInput = z.infer<typeof specInputSchema>;

// ─── Execute Tool ───────────────────────────────────────────────
export const executeInputSchema = z.object({
  action: z.enum(['start', 'plan_step', 'plan_complete', 'execute_start', 'execute_task', 'evaluate', 'status']),
  spec: z.object({
    version: z.string(),
    goal: z.string(),
    constraints: z.array(z.string()),
    acceptanceCriteria: z.array(z.string()),
    ontologySchema: z.object({ entities: z.array(z.any()), relations: z.array(z.any()) }),
    gestaltAnalysis: z.array(z.any()),
    metadata: z.object({
      specId: z.string(),
      interviewSessionId: z.string(),
      ambiguityScore: z.number(),
      generatedAt: z.string(),
    }),
  }).optional().describe('Spec specification (required for start)'),
  sessionId: z.string().optional().describe('Execute session ID'),
  stepResult: z.object({
    principle: z.enum(['figure_ground', 'closure', 'proximity', 'continuity']),
    classifiedACs: z.array(z.object({
      acIndex: z.number(),
      acText: z.string(),
      classification: z.enum(['figure', 'ground']),
      priority: z.enum(['critical', 'high', 'medium', 'low']),
      reasoning: z.string(),
    })).optional(),
    atomicTasks: z.array(z.object({
      taskId: z.string(),
      title: z.string(),
      description: z.string(),
      sourceAC: z.array(z.number()),
      isImplicit: z.boolean(),
      estimatedComplexity: z.enum(['low', 'medium', 'high']),
      dependsOn: z.array(z.string()),
    })).optional(),
    taskGroups: z.array(z.object({
      groupId: z.string(),
      name: z.string(),
      domain: z.string(),
      taskIds: z.array(z.string()),
      reasoning: z.string(),
    })).optional(),
    dagValidation: z.object({
      isValid: z.boolean(),
      hasCycles: z.boolean(),
      cycleDetails: z.array(z.string()).optional(),
      hasConflicts: z.boolean(),
      conflictDetails: z.array(z.string()).optional(),
      topologicalOrder: z.array(z.string()),
      criticalPath: z.array(z.string()),
    }).optional(),
  }).optional().describe('Planning step result (required for plan_step)'),
  taskResult: z.object({
    taskId: z.string(),
    status: z.enum(['pending', 'in_progress', 'completed', 'failed', 'skipped']),
    output: z.string(),
    artifacts: z.array(z.string()),
  }).optional().describe('Task execution result (required for execute_task)'),
  structuralResult: z.object({
    commands: z.array(z.object({
      name: z.string(),
      command: z.string(),
      exitCode: z.number(),
      output: z.string(),
    })),
    allPassed: z.boolean(),
  }).optional().describe('Structural check results (required for evaluate after structural stage)'),
  evaluationResult: z.object({
    verifications: z.array(z.object({
      acIndex: z.number(),
      satisfied: z.boolean(),
      evidence: z.string(),
      gaps: z.array(z.string()),
    })),
    overallScore: z.number().min(0).max(1),
    goalAlignment: z.number().min(0).max(1).optional().default(0),
    recommendations: z.array(z.string()),
  }).optional().describe('Evaluation result (optional for evaluate action)'),
});

export type ExecuteInput = z.infer<typeof executeInputSchema>;

// ─── Status Tool ────────────────────────────────────────────────
export const statusInputSchema = z.object({
  sessionId: z.string().optional(),
});

export type StatusInput = z.infer<typeof statusInputSchema>;
