import { z } from 'zod';

// ─── Interview Tool ─────────────────────────────────────────────
export const interviewInputSchema = z.object({
  action: z.enum(['start', 'respond', 'score', 'complete']),
  topic: z.string().optional(),
  sessionId: z.string().optional(),
  response: z.string().optional(),
  cwd: z.string().optional(),
  generatedQuestion: z.string().optional()
    .describe('Question generated by the caller LLM (passthrough mode)'),
  ambiguityScore: z.object({
    goalClarity: z.number().min(0).max(1),
    constraintClarity: z.number().min(0).max(1),
    successCriteria: z.number().min(0).max(1),
    priorityClarity: z.number().min(0).max(1),
    contextClarity: z.number().min(0).max(1).optional(),
    contradictions: z.array(z.string()).optional(),
  }).optional().describe('Ambiguity scores computed by the caller LLM (passthrough mode)'),
});

export type InterviewInput = z.infer<typeof interviewInputSchema>;

// ─── Spec Tool ──────────────────────────────────────────────────
export const specInputSchema = z.object({
  sessionId: z.string(),
  force: z.boolean().optional().default(false),
  spec: z.object({
    goal: z.string(),
    constraints: z.array(z.string()),
    acceptanceCriteria: z.array(z.string()),
    ontologySchema: z.object({ entities: z.array(z.any()), relations: z.array(z.any()) }),
    gestaltAnalysis: z.array(z.any()),
  }).optional().describe('Externally generated spec (passthrough mode)'),
});

export type SpecInput = z.infer<typeof specInputSchema>;

// ─── Execute Tool ───────────────────────────────────────────────
export const executeInputSchema = z.object({
  action: z.enum([
    'start', 'plan_step', 'plan_complete', 'execute_start', 'execute_task', 'evaluate', 'status',
    'evolve_fix', 'evolve', 'evolve_patch', 'evolve_re_execute',
    'evolve_lateral', 'evolve_lateral_result',
    'role_match', 'role_consensus',
  ]),
  spec: z.object({
    version: z.string(),
    goal: z.string(),
    constraints: z.array(z.string()),
    acceptanceCriteria: z.array(z.string()),
    ontologySchema: z.object({ entities: z.array(z.any()), relations: z.array(z.any()) }),
    gestaltAnalysis: z.array(z.any()),
    metadata: z.object({
      specId: z.string(),
      interviewSessionId: z.string(),
      ambiguityScore: z.number(),
      generatedAt: z.string(),
    }),
  }).optional().describe('Spec specification (required for start)'),
  sessionId: z.string().optional().describe('Execute session ID'),
  stepResult: z.object({
    principle: z.enum(['figure_ground', 'closure', 'proximity', 'continuity']),
    classifiedACs: z.array(z.object({
      acIndex: z.number(),
      acText: z.string(),
      classification: z.enum(['figure', 'ground']),
      priority: z.enum(['critical', 'high', 'medium', 'low']),
      reasoning: z.string(),
    })).optional(),
    atomicTasks: z.array(z.object({
      taskId: z.string(),
      title: z.string(),
      description: z.string(),
      sourceAC: z.array(z.number()),
      isImplicit: z.boolean(),
      estimatedComplexity: z.enum(['low', 'medium', 'high']),
      dependsOn: z.array(z.string()),
    })).optional(),
    taskGroups: z.array(z.object({
      groupId: z.string(),
      name: z.string(),
      domain: z.string(),
      taskIds: z.array(z.string()),
      reasoning: z.string(),
    })).optional(),
    dagValidation: z.object({
      isValid: z.boolean(),
      hasCycles: z.boolean(),
      cycleDetails: z.array(z.string()).optional(),
      hasConflicts: z.boolean(),
      conflictDetails: z.array(z.string()).optional(),
      topologicalOrder: z.array(z.string()),
      criticalPath: z.array(z.string()),
    }).optional(),
  }).optional().describe('Planning step result (required for plan_step)'),
  taskResult: z.object({
    taskId: z.string(),
    status: z.enum(['pending', 'in_progress', 'completed', 'failed', 'skipped']),
    output: z.string(),
    artifacts: z.array(z.string()),
  }).optional().describe('Task execution result (required for execute_task)'),
  structuralResult: z.object({
    commands: z.array(z.object({
      name: z.string(),
      command: z.string(),
      exitCode: z.number(),
      output: z.string(),
    })),
    allPassed: z.boolean(),
  }).optional().describe('Structural check results (required for evaluate after structural stage)'),
  evaluationResult: z.object({
    verifications: z.array(z.object({
      acIndex: z.number(),
      satisfied: z.boolean(),
      evidence: z.string(),
      gaps: z.array(z.string()),
    })),
    overallScore: z.number().min(0).max(1),
    goalAlignment: z.number().min(0).max(1).optional().default(0),
    recommendations: z.array(z.string()),
  }).optional().describe('Evaluation result (optional for evaluate action)'),

  // ─── Evolution Loop Fields ────────────────────────────────
  fixTasks: z.array(z.object({
    taskId: z.string(),
    failedCommand: z.string(),
    errorOutput: z.string(),
    fixDescription: z.string(),
    artifacts: z.array(z.string()),
  })).optional().describe('Fix task results (required for evolve_fix after fix stage)'),

  specPatch: z.object({
    acceptanceCriteria: z.array(z.string()).optional(),
    constraints: z.array(z.string()).optional(),
    ontologySchema: z.object({
      entities: z.array(z.object({
        name: z.string(),
        description: z.string(),
        attributes: z.array(z.string()),
      })).optional(),
      relations: z.array(z.object({
        from: z.string(),
        to: z.string(),
        type: z.string(),
      })).optional(),
    }).optional(),
  }).optional().describe('Spec patch for contextual evolution (required for evolve_patch)'),

  reExecuteTaskResult: z.object({
    taskId: z.string(),
    status: z.enum(['pending', 'in_progress', 'completed', 'failed', 'skipped']),
    output: z.string(),
    artifacts: z.array(z.string()),
  }).optional().describe('Re-execution task result (required for evolve_re_execute)'),

  terminateReason: z.enum(['caller']).optional()
    .describe('Caller-initiated termination (use with evolve action)'),

  // ─── Role Agent System Fields ────────────────────────────
  matchResult: z.array(z.object({
    agentName: z.string(),
    domain: z.array(z.string()),
    relevanceScore: z.number().min(0).max(1),
    reasoning: z.string(),
  })).optional().describe('Role match results from LLM (for role_match action, call 2)'),

  perspectives: z.array(z.object({
    agentName: z.string(),
    perspective: z.string(),
    confidence: z.number().min(0).max(1),
  })).optional().describe('Role perspectives from parallel LLM calls (for role_consensus action, call 1)'),

  consensus: z.object({
    consensus: z.string(),
    conflictResolutions: z.array(z.string()),
    perspectives: z.array(z.object({
      agentName: z.string(),
      perspective: z.string(),
      confidence: z.number().min(0).max(1),
    })),
  }).optional().describe('Synthesized consensus result (for role_consensus action, call 2)'),

  lateralResult: z.object({
    persona: z.enum(['multistability', 'simplicity', 'reification', 'invariance']),
    specPatch: z.object({
      acceptanceCriteria: z.array(z.string()).optional(),
      constraints: z.array(z.string()).optional(),
      ontologySchema: z.object({
        entities: z.array(z.object({
          name: z.string(),
          description: z.string(),
          attributes: z.array(z.string()),
        })).optional(),
        relations: z.array(z.object({
          from: z.string(),
          to: z.string(),
          type: z.string(),
        })).optional(),
      }).optional(),
    }),
    description: z.string(),
  }).optional().describe('Lateral thinking result (required for evolve_lateral_result)'),
});

export type ExecuteInput = z.infer<typeof executeInputSchema>;

// ─── Create Agent Tool ──────────────────────────────────────────
export const agentCreateInputSchema = z.object({
  action: z.enum(['start', 'submit']),
  sessionId: z.string().describe('The interview session ID'),
  agentContent: z.string().optional()
    .describe('Complete AGENT.md content (frontmatter + body) to validate and save (required for submit)'),
  cwd: z.string().optional()
    .describe('Working directory where agents/ will be created (defaults to process.cwd())'),
});

export type AgentCreateInput = z.infer<typeof agentCreateInputSchema>;

// ─── Status Tool ────────────────────────────────────────────────
export const statusInputSchema = z.object({
  sessionId: z.string().optional(),
});

export type StatusInput = z.infer<typeof statusInputSchema>;
