import { z } from 'zod';

// ─── Shared Spec Sub-schemas ────────────────────────────────────
// Spec의 ontology/gestaltAnalysis 필드를 구체화한 로컬 스키마.
// src/core/types.ts의 OntologyEntity, OntologyRelation, GestaltAnalysis와 정합.
const ontologyEntitySchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  attributes: z.array(z.string()).optional(),
});
const ontologyRelationSchema = z.object({
  from: z.string(),
  to: z.string(),
  type: z.string(),
});
const gestaltAnalysisItemSchema = z.object({
  principle: z.string(),
  finding: z.string(),
  confidence: z.number().min(0).max(1).optional(),
});

// ─── Interview Tool ─────────────────────────────────────────────
export const interviewInputSchema = z.object({
  action: z.enum(['start', 'respond', 'score', 'complete', 'compress']),
  topic: z.string().optional(),
  sessionId: z
    .string()
    .optional()
    .describe("Interview session ID. 'latest'(가장 최근 갱신)도 가능."),
  response: z.string().optional(),
  cwd: z.string().optional(),
  generatedQuestion: z
    .string()
    .optional()
    .describe('Question generated by the caller LLM (passthrough mode)'),
  resolutionScore: z
    .object({
      goalClarity: z.number().min(0).max(1),
      constraintClarity: z.number().min(0).max(1),
      successCriteria: z.number().min(0).max(1),
      priorityClarity: z.number().min(0).max(1),
      contextClarity: z.number().min(0).max(1).optional(),
      contradictions: z.array(z.string()).optional(),
    })
    .optional()
    .describe('Resolution scores computed by the caller LLM (passthrough mode)'),
  compressedSummary: z
    .string()
    .optional()
    .describe('Compressed summary generated by caller LLM (required for compress action)'),
});

export type InterviewInput = z.infer<typeof interviewInputSchema>;

// ─── Spec Tool ──────────────────────────────────────────────────
export const specInputSchema = z.object({
  sessionId: z
    .string()
    .optional()
    .describe(
      "Interview session ID (required when not using text input). 'latest'(가장 최근 갱신)도 가능.",
    ),
  text: z
    .string()
    .optional()
    .describe('Plain text description to generate spec directly without interview'),
  template: z
    .string()
    .optional()
    .describe('Template ID to use as base (rest-api, react-dashboard, cli-tool)'),
  force: z.boolean().optional().default(false),
  verbose: z
    .boolean()
    .optional()
    .default(true)
    .describe(
      'When false, omit large prompt fields (systemPrompt, specPrompt) from responses to reduce token usage',
    ),
  spec: z
    .object({
      goal: z.string(),
      constraints: z.array(z.string()),
      acceptanceCriteria: z.array(z.string()),
      ontologySchema: z.object({
        entities: z.array(ontologyEntitySchema),
        relations: z.array(ontologyRelationSchema),
      }),
      gestaltAnalysis: z.array(gestaltAnalysisItemSchema),
    })
    .optional()
    .describe('Externally generated spec (passthrough mode)'),
});

export type SpecInput = z.infer<typeof specInputSchema>;

// ─── Execute Tool ───────────────────────────────────────────────
export const executeInputSchema = z.object({
  action: z.enum([
    'start',
    'plan_step',
    'plan_complete',
    'execute_start',
    'execute_task',
    'evaluate',
    'status',
    'resume',
    'audit',
    'spawn',
    'evolve_fix',
    'evolve',
    'evolve_patch',
    'evolve_re_execute',
    'evolve_lateral',
    'evolve_lateral_result',
    'role_match',
    'role_consensus',
    'review_start',
    'review_submit',
    'review_consensus',
    'review_fix',
    'review_publish',
    'evolution_viz',
  ]),
  spec: z
    .object({
      version: z.string(),
      goal: z.string(),
      constraints: z.array(z.string()),
      acceptanceCriteria: z.array(z.string()),
      ontologySchema: z.object({
        entities: z.array(ontologyEntitySchema),
        relations: z.array(ontologyRelationSchema),
      }),
      gestaltAnalysis: z.array(gestaltAnalysisItemSchema),
      metadata: z.object({
        specId: z.string(),
        interviewSessionId: z.string(),
        resolutionScore: z.number().nullable(),
        generatedAt: z.string(),
      }),
    })
    .optional()
    .describe('Spec specification (required for start)'),
  sessionId: z
    .string()
    .optional()
    .describe("Execute session ID. 'active'(현재 활성 세션) 또는 'latest'(가장 최근 갱신)도 가능."),
  changedFiles: z
    .array(z.string())
    .optional()
    .describe('Changed file paths for direct review (without execute session)'),
  repoRoot: z
    .string()
    .optional()
    .describe(
      'Repository root for direct review mode. prId 갈래에서는 로컬 PR 저장소 경로다 (생략하면 프로세스의 현재 작업 디렉토리).',
    ),
  codeGraphRepoRoot: z
    .string()
    .optional()
    .describe(
      'Repo root path for blast-radius based test filtering (optional, requires code-graph.db)',
    ),
  cwd: z.string().optional().describe('Working directory for rule file creation'),
  client: z
    .enum(['claude-code', 'codex', 'both', 'grok'])
    .optional()
    .describe('Host client for active context recording (overrides server config per call)'),
  stepResult: z
    .object({
      principle: z.enum(['figure_ground', 'closure', 'proximity', 'continuity']),
      classifiedACs: z
        .array(
          z.object({
            acIndex: z.number(),
            acText: z.string(),
            classification: z.enum(['figure', 'ground']),
            priority: z.enum(['critical', 'high', 'medium', 'low']),
            reasoning: z.string(),
          }),
        )
        .optional(),
      atomicTasks: z
        .array(
          z.object({
            taskId: z.string(),
            title: z.string(),
            description: z.string(),
            sourceAC: z.array(z.number()),
            isImplicit: z.boolean(),
            estimatedComplexity: z.enum(['low', 'medium', 'high']),
            dependsOn: z.array(z.string()),
          }),
        )
        .optional(),
      taskGroups: z
        .array(
          z.object({
            groupId: z.string(),
            name: z.string(),
            domain: z.string(),
            taskIds: z.array(z.string()),
            reasoning: z.string(),
          }),
        )
        .optional(),
      dagValidation: z
        .object({
          isValid: z.boolean(),
          hasCycles: z.boolean(),
          cycleDetails: z.array(z.string()).optional(),
          hasConflicts: z.boolean(),
          conflictDetails: z.array(z.string()).optional(),
          topologicalOrder: z.array(z.string()),
          criticalPath: z.array(z.string()),
        })
        .optional(),
    })
    .optional()
    .describe('Planning step result (required for plan_step)'),
  taskResult: z
    .object({
      taskId: z.string(),
      status: z.enum(['pending', 'in_progress', 'completed', 'failed', 'skipped']),
      output: z.string(),
      artifacts: z.array(z.string()),
      suggestedFiles: z.array(z.string()).optional(),
    })
    .optional()
    .describe('Task execution result (required for execute_task)'),
  structuralResult: z
    .object({
      commands: z.array(
        z.object({
          name: z.string(),
          command: z.string(),
          exitCode: z.number(),
          output: z.string(),
        }),
      ),
      allPassed: z.boolean(),
    })
    .optional()
    .describe('Structural check results (required for evaluate after structural stage)'),
  evaluationResult: z
    .object({
      verifications: z.array(
        z.object({
          acIndex: z.number(),
          satisfied: z.boolean(),
          evidence: z.string(),
          gaps: z.array(z.string()),
        }),
      ),
      overallScore: z.number().min(0).max(1),
      goalAlignment: z.number().min(0).max(1).optional().default(0),
      recommendations: z.array(z.string()),
    })
    .optional()
    .describe('Evaluation result (optional for evaluate action)'),

  // ─── Evolution Loop Fields ────────────────────────────────
  fixTasks: z
    .array(
      z.object({
        taskId: z.string(),
        failedCommand: z.string(),
        errorOutput: z.string(),
        fixDescription: z.string(),
        artifacts: z.array(z.string()),
      }),
    )
    .optional()
    .describe('Fix task results (required for evolve_fix after fix stage)'),

  specPatch: z
    .object({
      acceptanceCriteria: z.array(z.string()).optional(),
      constraints: z.array(z.string()).optional(),
      ontologySchema: z
        .object({
          entities: z
            .array(
              z.object({
                name: z.string(),
                description: z.string(),
                attributes: z.array(z.string()),
              }),
            )
            .optional(),
          relations: z
            .array(
              z.object({
                from: z.string(),
                to: z.string(),
                type: z.string(),
              }),
            )
            .optional(),
        })
        .optional(),
    })
    .optional()
    .describe('Spec patch for contextual evolution (required for evolve_patch)'),

  reExecuteTaskResult: z
    .object({
      taskId: z.string(),
      status: z.enum(['pending', 'in_progress', 'completed', 'failed', 'skipped']),
      output: z.string(),
      artifacts: z.array(z.string()),
    })
    .optional()
    .describe('Re-execution task result (required for evolve_re_execute)'),

  terminateReason: z
    .enum(['caller'])
    .optional()
    .describe('Caller-initiated termination (use with evolve action)'),

  // ─── Role Agent System Fields ────────────────────────────
  matchResult: z
    .array(
      z.object({
        agentName: z.string(),
        domain: z.array(z.string()),
        relevanceScore: z.number().min(0).max(1),
        reasoning: z.string(),
      }),
    )
    .optional()
    .describe('Role match results from LLM (for role_match action, call 2)'),

  perspectives: z
    .array(
      z.object({
        agentName: z.string(),
        perspective: z.string(),
        confidence: z.number().min(0).max(1),
      }),
    )
    .optional()
    .describe('Role perspectives from parallel LLM calls (for role_consensus action, call 1)'),

  consensus: z
    .object({
      consensus: z.string(),
      conflictResolutions: z.array(z.string()),
      perspectives: z.array(
        z.object({
          agentName: z.string(),
          perspective: z.string(),
          confidence: z.number().min(0).max(1),
        }),
      ),
    })
    .optional()
    .describe('Synthesized consensus result (for role_consensus action, call 2)'),

  lateralResult: z
    .object({
      persona: z.enum(['multistability', 'simplicity', 'reification', 'invariance']),
      specPatch: z.object({
        acceptanceCriteria: z.array(z.string()).optional(),
        constraints: z.array(z.string()).optional(),
        ontologySchema: z
          .object({
            entities: z
              .array(
                z.object({
                  name: z.string(),
                  description: z.string(),
                  attributes: z.array(z.string()),
                }),
              )
              .optional(),
            relations: z
              .array(
                z.object({
                  from: z.string(),
                  to: z.string(),
                  type: z.string(),
                }),
              )
              .optional(),
          })
          .optional(),
      }),
      description: z.string(),
    })
    .optional()
    .describe('Lateral thinking result (required for evolve_lateral_result)'),

  // ─── Audit Fields ─────────────────────────────────────────
  codebaseSnapshot: z
    .string()
    .optional()
    .describe('Codebase snapshot text for audit (required for audit action, call 1)'),
  auditResult: z
    .object({
      implementedACs: z.array(z.number()),
      partialACs: z.array(z.number()),
      missingACs: z.array(z.number()),
      gapAnalysis: z.string(),
    })
    .optional()
    .describe('Audit result (required for audit action, call 2)'),

  // ─── Sub-task Spawning Fields ──────────────────────────────
  parentTaskId: z.string().optional().describe('Parent task ID for spawning sub-tasks'),
  subTasks: z
    .array(
      z.object({
        title: z.string(),
        description: z.string(),
        dependsOn: z.array(z.string()).optional().default([]),
      }),
    )
    .optional()
    .describe('Sub-tasks to spawn (required for spawn action)'),

  // ─── Verbosity Control ────────────────────────────────────
  verbose: z
    .boolean()
    .optional()
    .default(true)
    .describe(
      'When false, omit large prompt fields (systemPrompt, planningPrompt, taskPrompt, etc.) from responses to reduce token usage',
    ),

  // Code Review
  reviewAgentName: z.string().optional().describe('Review agent name (required for review_submit)'),
  reviewResult: z
    .object({
      issues: z.array(
        z.object({
          id: z.string(),
          severity: z.enum(['critical', 'high', 'warning']),
          category: z.string(),
          file: z.string(),
          line: z.number().optional(),
          message: z.string(),
          suggestion: z.string(),
        }),
      ),
      approved: z.boolean(),
      summary: z.string(),
    })
    .optional()
    .describe('Individual agent review result (required for review_submit)'),
  reviewConsensus: z
    .object({
      mergedIssues: z.array(
        z.object({
          id: z.string(),
          severity: z.enum(['critical', 'high', 'warning']),
          category: z.string(),
          file: z.string(),
          line: z.number().optional(),
          message: z.string(),
          suggestion: z.string(),
          reportedBy: z.string(),
        }),
      ),
      approvedBy: z.array(z.string()),
      blockedBy: z.array(z.string()),
      summary: z.string(),
      overallApproved: z.boolean(),
    })
    .optional()
    .describe('Merged review consensus (required for review_consensus)'),
  continuityVerdict: z
    .object({
      coherent: z.boolean(),
      driftFindings: z.array(
        z.object({
          axis: z.enum(['goal', 'consistency', 'drift']),
          file: z.string().optional(),
          message: z.string(),
        }),
      ),
      escalate: z.boolean(),
      summary: z.string(),
    })
    .optional()
    .describe(
      'Continuity instance (정합 심급) verdict from continuity-judge (optional, for review_consensus). coherent=false blocks even without defects; escalate=true routes to re-spec instead of review_fix.',
    ),
  reviewSessionId: z
    .string()
    .optional()
    .describe(
      'Review session ID (required for review_submit, review_consensus, review_fix, review_publish)',
    ),
  prId: z
    .string()
    .optional()
    .describe(
      '로컬 PR id. review_start에 주면 그 PR의 변경 파일과 저장소 경로로 리뷰를 연다 (sessionId·changedFiles보다 우선). review_publish에 필요하며, review_start에서 이미 준 세션이면 생략할 수 있다.',
    ),
  prReviewer: z
    .string()
    .optional()
    .describe(
      'review_publish가 남길 판정의 리뷰어 이름. 생략하면 GESTALT_ACTOR 환경변수, 그것도 없으면 gestalt:review를 쓴다. 개별 코멘트 작성자는 이 값이 아니라 각 지적의 reportedBy다.',
    ),
});

export type ExecuteInput = z.infer<typeof executeInputSchema>;
export const executeToolSchema = executeInputSchema.shape;

// ─── Create Agent Tool ──────────────────────────────────────────
export const agentCreateInputSchema = z.object({
  action: z.enum(['start', 'submit']),
  sessionId: z.string().describe("The interview session ID. 'latest'(가장 최근 갱신)도 가능."),
  agentContent: z
    .string()
    .optional()
    .describe(
      'Complete AGENT.md content (frontmatter + body) to validate and save (required for submit)',
    ),
  cwd: z
    .string()
    .optional()
    .describe('Working directory where agents/ will be created (defaults to process.cwd())'),
});

export type AgentCreateInput = z.infer<typeof agentCreateInputSchema>;

// ─── Benchmark Tool ─────────────────────────────────────────────
export const benchmarkInputSchema = z.object({
  action: z.enum(['start', 'respond', 'status']),
  scenario: z
    .string()
    .optional()
    .describe('Scenario name (required for start): auth-system, dashboard, api-gateway'),
  benchmarkSessionId: z
    .string()
    .optional()
    .describe('Benchmark session ID (required for respond/status)'),
  response: z
    .string()
    .optional()
    .describe('JSON response from the caller LLM (required for respond)'),
  usage: z
    .object({
      inputTokens: z.number(),
      outputTokens: z.number(),
    })
    .optional()
    .describe('Token usage from the caller LLM call (optional, for metrics)'),
});

export type BenchmarkInput = z.infer<typeof benchmarkInputSchema>;

// ─── Code Graph Tool ────────────────────────────────────────────
export const codeGraphInputSchema = z.object({
  action: z
    .enum(['build', 'blast_radius', 'diff_radius', 'query', 'stats', 'db_exists'])
    .describe(
      'build: index codebase, blast_radius: committed changes, diff_radius: uncommitted changes, query: graph query, stats: show stats, db_exists: check DB',
    ),
  repoRoot: z.string().describe('Absolute path to the repository root'),
  // build 전용
  include: z.array(z.string()).optional().describe('Glob patterns to include (default: **/**)'),
  exclude: z.array(z.string()).optional().describe('Glob patterns to exclude'),
  mode: z.enum(['full', 'incremental']).optional().describe('Build mode (default: full)'),
  // blast_radius 전용
  changedFiles: z
    .array(z.string())
    .optional()
    .describe('Changed file paths (auto-detected from git diff if omitted)'),
  base: z.string().optional().describe('Git base ref for diff (default: HEAD~1)'),
  maxDepth: z.number().optional().describe('BFS depth limit (default: 2)'),
  // diff_radius 전용
  diffMode: z
    .enum(['staged', 'unstaged', 'all'])
    .optional()
    .describe(
      'diff_radius mode: staged=git diff --cached, unstaged=git diff, all=git diff HEAD (default: all)',
    ),
  // query 전용
  pattern: z
    .enum(['callers_of', 'callees_of', 'tests_for', 'imports_of'])
    .optional()
    .describe('Query pattern (required for query action)'),
  target: z.string().optional().describe('Target function/file name (required for query action)'),
});

export type CodeGraphInput = z.infer<typeof codeGraphInputSchema>;

// ─── Status Tool ────────────────────────────────────────────────
export const statusInputSchema = z.object({
  sessionId: z
    .string()
    .optional()
    .describe(
      "Session ID. 'latest'(가장 최근 갱신)도 가능하고, sessionType='execute'/'all'이면 'active'(현재 활성 실행 세션)도 가능.",
    ),
  sessionType: z.enum(['interview', 'execute', 'all']).optional().default('all'),
});

export type StatusInput = z.infer<typeof statusInputSchema>;

// ─── Graph Visualize Tool ────────────────────────────────────────
export const graphVisualizeInputSchema = z.object({
  repoRoot: z.string().describe('Absolute path to the repository root'),
  port: z
    .number()
    .optional()
    .describe('Preferred port (default: 7891, auto-increments on conflict)'),
});

export type GraphVisualizeInput = z.infer<typeof graphVisualizeInputSchema>;

// ─── Local PR Tool ────────────────────────────────────────────────
/**
 * `ges_pr`이 받는 액션.
 *
 * 서버 등록(`server.tool`)이 이 배열을 그대로 쓴다. 목록을 두 곳에 적으면 하나가
 * 뒤처진다 — 실제로 checkout을 붙일 때 등록 enum만 열 개로 남아 MCP로는 부를 수
 * 없는 액션이 생겼다.
 */
export const PR_ACTIONS = [
  'create',
  'list',
  'get',
  'diff',
  'comment',
  'resolve',
  'review',
  'update',
  'edit',
  'merge',
  'close',
  'checkout',
  'checkout_remove',
] as const;

export const prInputSchema = z.object({
  action: z
    .enum(PR_ACTIONS)
    .describe(
      'create: 새 PR, list: 목록, get: 단건 조회, diff: 변경 내용, comment: 코멘트 추가, resolve: 코멘트 스레드 해결, review: 판정 기록, update: head 갱신, edit: 제목·본문 수정, merge: 머지, close: 닫기, checkout: head를 임시 워크트리로 떼어냄, checkout_remove: 그 워크트리 정리',
    ),
  repoRoot: z.string().optional().describe('저장소 경로 (기본값: 현재 작업 디렉토리)'),
  id: z.string().optional().describe('PR id. create와 list를 제외한 모든 action에 필요하다'),
  // create 전용
  title: z.string().optional().describe('create에 필요. edit에서는 새 제목'),
  base: z.string().optional().describe('create 전용: 기준 브랜치(기본 main)'),
  head: z.string().optional().describe('create: 리뷰 대상 브랜치(기본 HEAD), update: 옮겨갈 커밋'),
  // create, comment, resolve, review, merge, close 공통
  author: z
    .string()
    .optional()
    .describe("작업자. 형식 예: 'claude-code:main', 'codex:worker-2'. 안 주면 human:local"),
  body: z
    .string()
    .optional()
    .describe('create: PR 본문, comment: 코멘트 본문, edit: 새 PR 본문(빈 문자열이면 비운다)'),
  // list 전용
  status: z
    .enum(['open', 'changes_requested', 'merged', 'closed'])
    .optional()
    .describe('list 필터'),
  // comment 전용
  path: z.string().optional().describe('comment에 필요. 코멘트가 달릴 파일 경로'),
  line: z.number().optional().describe('comment: head 기준 라인. 생략하면 파일 전반'),
  replyTo: z.string().optional().describe('comment: 답글일 때 부모 코멘트 id'),
  // resolve 전용
  commentId: z.string().optional().describe('resolve에 필요'),
  // review 전용
  verdict: z.enum(['approve', 'request_changes', 'comment']).optional().describe('review에 필요'),
  summary: z.string().optional().describe('review: 판정 요약'),
  // merge 전용
  deleteBranch: z.boolean().optional().describe('merge: 머지 후 head 브랜치 삭제 여부'),
  // close 전용
  reason: z.string().optional().describe('close: 닫는 이유'),
  // checkout_remove 전용
  force: z
    .boolean()
    .optional()
    .describe('checkout_remove: 커밋 안 된 변경이 있어도 지운다. 기본은 안 지우고 알린다'),
});

export type PrInput = z.infer<typeof prInputSchema>;
