import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { loadConfig, type GestaltConfig } from '../core/config.js';
import { log } from '../core/log.js';
import { EventStore } from '../events/store.js';
import { AnthropicAdapter } from '../llm/adapter.js';
import { InterviewEngine } from '../interview/engine.js';
import { PassthroughEngine } from '../interview/passthrough-engine.js';
import { SpecGenerator } from '../spec/generator.js';
import { PassthroughSpecGenerator } from '../spec/passthrough-generator.js';
import { SkillRegistry } from '../skills/registry.js';
import { handleInterview } from './tools/interview.js';
import { handleInterviewPassthrough } from './tools/interview-passthrough.js';
import { handleSpec } from './tools/spec.js';
import { handleSpecPassthrough } from './tools/spec-passthrough.js';
import { handleExecutePassthrough } from './tools/execute-passthrough.js';
import { handleStatus } from './tools/status.js';
import { interviewInputSchema, specInputSchema, executeInputSchema, statusInputSchema } from './schemas.js';
import { PassthroughExecuteEngine } from '../execute/passthrough-engine.js';

export async function createMcpServer(configOverrides?: Partial<GestaltConfig>) {
  const config = loadConfig(configOverrides);
  const eventStore = new EventStore(config.dbPath);
  const skillRegistry = new SkillRegistry(config.skillsDir);

  skillRegistry.loadAll();

  const isPassthrough = !config.anthropicApiKey;

  const server = new McpServer({
    name: 'gestalt',
    version: '0.1.0',
  });

  if (isPassthrough) {
    // ─── Passthrough mode: no API key, prompts returned to caller ───
    const ptEngine = new PassthroughEngine(eventStore);
    const ptSpecGen = new PassthroughSpecGenerator(eventStore);

    server.tool(
      'ges_interview',
      'Conduct a Gestalt-driven interview (passthrough mode — returns prompts for caller LLM to generate questions/scores). Actions: start, respond, score, complete.',
      {
        action: z.enum(['start', 'respond', 'score', 'complete']).describe(
          'start: begin interview, respond: answer a question, score: check ambiguity, complete: finish interview',
        ),
        topic: z.string().optional().describe('Topic for the interview (required for start)'),
        sessionId: z.string().optional().describe('Session ID (required for respond/score/complete)'),
        response: z.string().optional().describe('User response to the current question (required for respond)'),
        cwd: z.string().optional().describe('Working directory for brownfield detection'),
        generatedQuestion: z.string().optional().describe('Question generated by the caller LLM (required for respond in passthrough mode)'),
        ambiguityScore: z.object({
          goalClarity: z.number().min(0).max(1),
          constraintClarity: z.number().min(0).max(1),
          successCriteria: z.number().min(0).max(1),
          priorityClarity: z.number().min(0).max(1),
          contextClarity: z.number().min(0).max(1).optional(),
          contradictions: z.array(z.string()).optional(),
        }).optional().describe('Ambiguity scores computed by the caller LLM'),
      },
      (params) => {
        const input = interviewInputSchema.parse(params);
        const result = handleInterviewPassthrough(ptEngine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_generate_spec',
      'Generate a Spec specification (passthrough mode — returns prompt or validates externally generated spec).',
      {
        sessionId: z.string().describe('The interview session ID'),
        force: z.boolean().optional().default(false).describe(
          'Force generation even if ambiguity threshold is not met',
        ),
        spec: z.object({
          goal: z.string(),
          constraints: z.array(z.string()),
          acceptanceCriteria: z.array(z.string()),
          ontologySchema: z.object({ entities: z.array(z.any()), relations: z.array(z.any()) }),
          gestaltAnalysis: z.array(z.any()),
        }).optional().describe('Externally generated spec JSON to validate and store'),
      },
      (params) => {
        const input = specInputSchema.parse(params);
        const result = handleSpecPassthrough(ptEngine, ptSpecGen, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    const ptExecuteEngine = new PassthroughExecuteEngine(eventStore);

    server.tool(
      'ges_execute',
      'Execute a Spec specification using Gestalt principles (passthrough mode). Actions: start, plan_step, plan_complete, execute_start, execute_task, evaluate, status.',
      {
        action: z.enum(['start', 'plan_step', 'plan_complete', 'execute_start', 'execute_task', 'evaluate', 'status']).describe(
          'start: begin execution planning, plan_step: submit a planning step result, plan_complete: assemble final plan, execute_start: start task execution, execute_task: submit task result, evaluate: start/submit evaluation, status: check session status',
        ),
        spec: z.object({
          version: z.string(),
          goal: z.string(),
          constraints: z.array(z.string()),
          acceptanceCriteria: z.array(z.string()),
          ontologySchema: z.object({ entities: z.array(z.any()), relations: z.array(z.any()) }),
          gestaltAnalysis: z.array(z.any()),
          metadata: z.object({
            specId: z.string(),
            interviewSessionId: z.string(),
            ambiguityScore: z.number(),
            generatedAt: z.string(),
          }),
        }).optional().describe('Spec specification (required for start)'),
        sessionId: z.string().optional().describe('Execute session ID (required for plan_step/plan_complete/status)'),
        stepResult: z.object({
          principle: z.enum(['figure_ground', 'closure', 'proximity', 'continuity']),
          classifiedACs: z.array(z.any()).optional(),
          atomicTasks: z.array(z.any()).optional(),
          taskGroups: z.array(z.any()).optional(),
          dagValidation: z.object({
            isValid: z.boolean(),
            hasCycles: z.boolean(),
            cycleDetails: z.array(z.string()).optional(),
            hasConflicts: z.boolean(),
            conflictDetails: z.array(z.string()).optional(),
            topologicalOrder: z.array(z.string()),
            criticalPath: z.array(z.string()),
          }).optional(),
        }).optional().describe('Planning step result (required for plan_step)'),
        taskResult: z.object({
          taskId: z.string(),
          status: z.enum(['pending', 'in_progress', 'completed', 'failed', 'skipped']),
          output: z.string(),
          artifacts: z.array(z.string()),
        }).optional().describe('Task execution result (required for execute_task)'),
        evaluationResult: z.object({
          verifications: z.array(z.object({
            acIndex: z.number(),
            satisfied: z.boolean(),
            evidence: z.string(),
            gaps: z.array(z.string()),
          })),
          overallScore: z.number().min(0).max(1),
          recommendations: z.array(z.string()),
        }).optional().describe('Evaluation result (optional for evaluate action)'),
      },
      (params) => {
        const input = executeInputSchema.parse(params);
        const result = handleExecutePassthrough(ptExecuteEngine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_status',
      'Check the status of interview sessions.',
      {
        sessionId: z.string().optional().describe('Specific session ID to check (omit for all sessions)'),
      },
      (params) => {
        const input = statusInputSchema.parse(params);
        const result = handleStatusPassthrough(ptEngine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );
  } else {
    // ─── Normal mode: direct LLM calls ──────────────────────────
    const llm = new AnthropicAdapter(config.anthropicApiKey, config.model);
    const engine = new InterviewEngine(llm, eventStore);
    const specGenerator = new SpecGenerator(llm, eventStore);

    server.tool(
      'ges_interview',
      'Conduct a Gestalt-driven interview to clarify project requirements. Actions: start, respond, score, complete.',
      {
        action: z.enum(['start', 'respond', 'score', 'complete']).describe(
          'start: begin interview, respond: answer a question, score: check ambiguity, complete: finish interview',
        ),
        topic: z.string().optional().describe('Topic for the interview (required for start)'),
        sessionId: z.string().optional().describe('Session ID (required for respond/score/complete)'),
        response: z.string().optional().describe('User response to the current question (required for respond)'),
        cwd: z.string().optional().describe('Working directory for brownfield detection'),
      },
      async (params) => {
        const input = interviewInputSchema.parse(params);
        const result = await handleInterview(engine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_generate_spec',
      'Generate a Spec specification from a completed interview session.',
      {
        sessionId: z.string().describe('The interview session ID'),
        force: z.boolean().optional().default(false).describe(
          'Force generation even if ambiguity threshold is not met',
        ),
      },
      async (params) => {
        const input = specInputSchema.parse(params);
        const result = await handleSpec(engine, specGenerator, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_status',
      'Check the status of interview sessions.',
      {
        sessionId: z.string().optional().describe('Specific session ID to check (omit for all sessions)'),
      },
      (params) => {
        const input = statusInputSchema.parse(params);
        const result = handleStatus(engine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );
  }

  return { server, eventStore, skillRegistry };
}

// Status handler for passthrough mode — uses PassthroughEngine instead of InterviewEngine
function handleStatusPassthrough(
  engine: PassthroughEngine,
  input: { sessionId?: string },
): string {
  try {
    if (input.sessionId) {
      const session = engine.getSession(input.sessionId);
      return JSON.stringify({
        session: {
          sessionId: session.sessionId,
          topic: session.topic,
          status: session.status,
          projectType: session.projectType,
          totalRounds: session.rounds.length,
          answeredRounds: session.rounds.filter((r) => r.userResponse).length,
          ambiguityScore: session.ambiguityScore
            ? {
                overall: session.ambiguityScore.overall.toFixed(2),
                isReady: session.ambiguityScore.isReady,
              }
            : null,
          createdAt: session.createdAt,
          updatedAt: session.updatedAt,
        },
      }, null, 2);
    }

    const sessions = engine.listSessions();
    return JSON.stringify({
      sessions: sessions.map((s) => ({
        sessionId: s.sessionId,
        topic: s.topic,
        status: s.status,
        projectType: s.projectType,
        totalRounds: s.rounds.length,
        ambiguityScore: s.ambiguityScore?.overall.toFixed(2) ?? 'N/A',
        createdAt: s.createdAt,
      })),
      total: sessions.length,
    }, null, 2);
  } catch (e) {
    return JSON.stringify({
      error: e instanceof Error ? e.message : String(e),
    }, null, 2);
  }
}

export async function startMcpServer(configOverrides?: Partial<GestaltConfig>) {
  const config = loadConfig(configOverrides);
  const isPassthrough = !config.anthropicApiKey;
  const { server, skillRegistry } = await createMcpServer(configOverrides);

  skillRegistry.startWatching();

  const transport = new StdioServerTransport();
  await server.connect(transport);

  log(`MCP server started on stdio${isPassthrough ? ' (passthrough mode)' : ''}`);

  process.on('SIGINT', async () => {
    await skillRegistry.stopWatching();
    await server.close();
    process.exit(0);
  });
}
