import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { loadConfig, type GestaltConfig } from '../core/config.js';
import { log } from '../core/log.js';
import { getVersion, checkForUpdates, getCachedUpdateResult } from '../core/version.js';
import { EventStore } from '../events/store.js';
import { AnthropicAdapter } from '../llm/adapter.js';
import { InterviewEngine } from '../interview/engine.js';
import { PassthroughEngine } from '../interview/passthrough-engine.js';
import { SpecGenerator } from '../spec/generator.js';
import { PassthroughSpecGenerator } from '../spec/passthrough-generator.js';
import { SkillRegistry } from '../skills/registry.js';
import { AgentRegistry } from '../agent/registry.js';
import { handleInterview } from './tools/interview.js';
import { handleInterviewPassthrough } from './tools/interview-passthrough.js';
import { handleSpec } from './tools/spec.js';
import { handleSpecPassthrough } from './tools/spec-passthrough.js';
import { handleExecutePassthrough } from './tools/execute-passthrough.js';
import { handleCreateAgentPassthrough } from './tools/create-agent-passthrough.js';
import { handleStatus } from './tools/status.js';
import { handleBenchmarkPassthrough } from './tools/benchmark-passthrough.js';
import { handleAgentPassthrough } from './tools/agent-passthrough.js';
import { handleReviewPassthrough } from './tools/review-passthrough.js';
import { handleCodeGraphPassthrough } from './tools/code-graph-passthrough.js';
import { handleGraphVisualizePassthrough } from './tools/graph-visualize-passthrough.js';
import { PassthroughReviewEngine } from '../review/passthrough-engine.js';
import { interviewInputSchema, specInputSchema, executeInputSchema, agentCreateInputSchema, benchmarkInputSchema, statusInputSchema, codeGraphInputSchema, graphVisualizeInputSchema } from './schemas.js';
import { PassthroughExecuteEngine } from '../execute/passthrough-engine.js';
import { PassthroughAgentGenerator } from '../agent/passthrough-generator.js';
import { RoleAgentRegistry } from '../agent/role-agent-registry.js';
import { setNotificationsEnabled } from '../utils/notifier.js';

export async function createMcpServer(configOverrides?: Partial<GestaltConfig>) {
  const config = loadConfig(configOverrides);
  setNotificationsEnabled(config.notifications);
  const eventStore = new EventStore(config.dbPath);
  const skillRegistry = new SkillRegistry(config.skillsDir);
  const agentRegistry = new AgentRegistry(config.agentsDir);

  skillRegistry.loadAll();
  agentRegistry.loadAll();

  const isPassthrough = !config.llm.apiKey;

  const server = new McpServer({
    name: 'gestalt',
    version: getVersion(),
  });

  if (isPassthrough) {
    // ─── Passthrough mode: no API key, prompts returned to caller ───
    const ptEngine = new PassthroughEngine(eventStore, agentRegistry);
    const ptSpecGen = new PassthroughSpecGenerator(eventStore, agentRegistry);

    server.tool(
      'ges_interview',
      'Conduct a Gestalt-driven interview (passthrough mode — returns prompts for caller LLM to generate questions/scores). Actions: start, respond, score, complete.',
      {
        action: z.enum(['start', 'respond', 'score', 'complete']).describe(
          'start: begin interview, respond: answer a question, score: check resolution, complete: finish interview',
        ),
        topic: z.string().optional().describe('Topic for the interview (required for start)'),
        sessionId: z.string().optional().describe('Session ID (required for respond/score/complete)'),
        response: z.string().optional().describe('User response to the current question (required for respond)'),
        cwd: z.string().optional().describe('Working directory for brownfield detection'),
        generatedQuestion: z.string().optional().describe('Question generated by the caller LLM (required for respond in passthrough mode)'),
        resolutionScore: z.object({
          goalClarity: z.number().min(0).max(1),
          constraintClarity: z.number().min(0).max(1),
          successCriteria: z.number().min(0).max(1),
          priorityClarity: z.number().min(0).max(1),
          contextClarity: z.number().min(0).max(1).optional(),
          contradictions: z.array(z.string()).optional(),
        }).optional().describe('Resolution scores computed by the caller LLM'),
        record: z.boolean().optional().describe('Generate a GIF recording of the interview session on complete'),
      },
      (params) => {
        const input = interviewInputSchema.parse(params);
        const result = handleInterviewPassthrough(ptEngine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_generate_spec',
      'Generate a Spec specification (passthrough mode — returns prompt or validates externally generated spec).',
      {
        sessionId: z.string().optional().describe('Interview session ID (required when not using text input)'),
        text: z.string().optional().describe('Plain text description to generate spec directly without interview'),
        force: z.boolean().optional().default(false).describe(
          'Force generation even if resolution threshold is not met',
        ),
        spec: z.object({
          goal: z.string(),
          constraints: z.array(z.string()),
          acceptanceCriteria: z.array(z.string()),
          ontologySchema: z.object({ entities: z.array(z.any()), relations: z.array(z.any()) }),
          gestaltAnalysis: z.array(z.any()),
        }).optional().describe('Externally generated spec JSON to validate and store'),
      },
      (params) => {
        const input = specInputSchema.parse(params);
        const result = handleSpecPassthrough(ptEngine, ptSpecGen, input, agentRegistry);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    const roleAgentRegistry = new RoleAgentRegistry(config.roleAgentsDir, config.agentsDir, config.reviewAgentsDir);
    roleAgentRegistry.loadAll();

    const ptExecuteEngine = new PassthroughExecuteEngine(eventStore, agentRegistry, roleAgentRegistry);
    const ptReviewEngine = new PassthroughReviewEngine(eventStore);

    server.tool(
      'ges_execute',
      'Execute a Spec specification using Gestalt principles (passthrough mode). Actions: start, plan_step, plan_complete, execute_start, execute_task, evaluate, status, evolve_fix, evolve, evolve_patch, evolve_re_execute, evolve_lateral, evolve_lateral_result, review_start, review_submit, review_consensus, review_fix.',
      {
        action: z.enum([
          'start', 'plan_step', 'plan_complete', 'execute_start', 'execute_task', 'evaluate', 'status',
          'evolve_fix', 'evolve', 'evolve_patch', 'evolve_re_execute',
          'evolve_lateral', 'evolve_lateral_result',
          'role_match', 'role_consensus',
          'review_start', 'review_submit', 'review_consensus', 'review_fix',
        ]).describe(
          'start: begin execution planning, plan_step: submit a planning step result, plan_complete: assemble final plan, execute_start: start task execution, execute_task: submit task result, evaluate: start/submit evaluation, status: check session status, evolve_fix: start/submit structural fix, evolve: start contextual evolution, evolve_patch: submit spec patch, evolve_re_execute: submit re-execution task result, evolve_lateral: request next lateral thinking persona, evolve_lateral_result: submit lateral thinking result, review_start: start code review, review_submit: submit agent review, review_consensus: submit merged review, review_fix: start auto-fix loop',
        ),
        spec: z.object({
          version: z.string(),
          goal: z.string(),
          constraints: z.array(z.string()),
          acceptanceCriteria: z.array(z.string()),
          ontologySchema: z.object({ entities: z.array(z.any()), relations: z.array(z.any()) }),
          gestaltAnalysis: z.array(z.any()),
          metadata: z.object({
            specId: z.string(),
            interviewSessionId: z.string(),
            resolutionScore: z.number(),
            generatedAt: z.string(),
          }),
        }).optional().describe('Spec specification (required for start)'),
        sessionId: z.string().optional().describe('Execute session ID (required for plan_step/plan_complete/status)'),
        stepResult: z.object({
          principle: z.enum(['figure_ground', 'closure', 'proximity', 'continuity']),
          classifiedACs: z.array(z.any()).optional(),
          atomicTasks: z.array(z.any()).optional(),
          taskGroups: z.array(z.any()).optional(),
          dagValidation: z.object({
            isValid: z.boolean(),
            hasCycles: z.boolean(),
            cycleDetails: z.array(z.string()).optional(),
            hasConflicts: z.boolean(),
            conflictDetails: z.array(z.string()).optional(),
            topologicalOrder: z.array(z.string()),
            criticalPath: z.array(z.string()),
          }).optional(),
        }).optional().describe('Planning step result (required for plan_step)'),
        taskResult: z.object({
          taskId: z.string(),
          status: z.enum(['pending', 'in_progress', 'completed', 'failed', 'skipped']),
          output: z.string(),
          artifacts: z.array(z.string()),
        }).optional().describe('Task execution result (required for execute_task)'),
        evaluationResult: z.object({
          verifications: z.array(z.object({
            acIndex: z.number(),
            satisfied: z.boolean(),
            evidence: z.string(),
            gaps: z.array(z.string()),
          })),
          overallScore: z.number().min(0).max(1),
          goalAlignment: z.number().min(0).max(1).optional().default(0),
          recommendations: z.array(z.string()),
        }).optional().describe('Evaluation result (optional for evaluate action)'),
        structuralResult: z.object({
          commands: z.array(z.object({
            name: z.string(),
            command: z.string(),
            exitCode: z.number(),
            output: z.string(),
          })),
          allPassed: z.boolean(),
        }).optional().describe('Structural check results (required for evaluate after structural stage)'),
        fixTasks: z.array(z.object({
          taskId: z.string(),
          failedCommand: z.string(),
          errorOutput: z.string(),
          fixDescription: z.string(),
          artifacts: z.array(z.string()),
        })).optional().describe('Fix task results (for evolve_fix)'),
        specPatch: z.object({
          acceptanceCriteria: z.array(z.string()).optional(),
          constraints: z.array(z.string()).optional(),
          ontologySchema: z.object({
            entities: z.array(z.any()).optional(),
            relations: z.array(z.any()).optional(),
          }).optional(),
        }).optional().describe('Spec patch for contextual evolution (for evolve_patch)'),
        reExecuteTaskResult: z.object({
          taskId: z.string(),
          status: z.enum(['pending', 'in_progress', 'completed', 'failed', 'skipped']),
          output: z.string(),
          artifacts: z.array(z.string()),
        }).optional().describe('Re-execution task result (for evolve_re_execute)'),
        terminateReason: z.enum(['caller']).optional().describe('Caller-initiated termination'),
        lateralResult: z.object({
          persona: z.enum(['multistability', 'simplicity', 'reification', 'invariance']),
          specPatch: z.object({
            acceptanceCriteria: z.array(z.string()).optional(),
            constraints: z.array(z.string()).optional(),
            ontologySchema: z.object({
              entities: z.array(z.any()).optional(),
              relations: z.array(z.any()).optional(),
            }).optional(),
          }),
          description: z.string(),
        }).optional().describe('Lateral thinking result (for evolve_lateral_result)'),
        matchResult: z.array(z.object({
          agentName: z.string(),
          domain: z.array(z.string()),
          relevanceScore: z.number().min(0).max(1),
          reasoning: z.string(),
        })).optional().describe('Role match results (for role_match action)'),
        perspectives: z.array(z.object({
          agentName: z.string(),
          perspective: z.string(),
          confidence: z.number().min(0).max(1),
        })).optional().describe('Role perspectives (for role_consensus action)'),
        consensus: z.object({
          consensus: z.string(),
          conflictResolutions: z.array(z.string()),
          perspectives: z.array(z.object({
            agentName: z.string(),
            perspective: z.string(),
            confidence: z.number().min(0).max(1),
          })),
        }).optional().describe('Synthesized consensus (for role_consensus action)'),
      },
      async (params) => {
        const input = executeInputSchema.parse(params);
        // Route review actions to review engine
        if (input.action.startsWith('review_')) {
          const result = handleReviewPassthrough(ptReviewEngine, ptExecuteEngine, roleAgentRegistry, input);
          return { content: [{ type: 'text' as const, text: result }] };
        }
        const result = await handleExecutePassthrough(ptExecuteEngine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    const ptAgentGen = new PassthroughAgentGenerator(eventStore, roleAgentRegistry);

    server.tool(
      'ges_create_agent',
      'Create a custom Role Agent from a completed interview session (passthrough mode). Actions: start, submit.',
      {
        action: z.enum(['start', 'submit']).describe(
          'start: get agent creation context with prompts, submit: validate and save AGENT.md',
        ),
        sessionId: z.string().describe('The interview session ID'),
        agentContent: z.string().optional().describe(
          'Complete AGENT.md content (frontmatter + body) to validate and save (required for submit)',
        ),
        cwd: z.string().optional().describe(
          'Working directory where agents/{name}/AGENT.md will be created (defaults to process.cwd())',
        ),
      },
      (params) => {
        const input = agentCreateInputSchema.parse(params);
        const result = handleCreateAgentPassthrough(ptEngine, ptAgentGen, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_agent',
      'List available agents or retrieve a specific agent\'s system prompt for standalone use — no pipeline required. Actions: list (get all role/review agents), get (retrieve agent by name).',
      {
        action: z.enum(['list', 'get']).describe(
          'list: get all available agents grouped by type, get: retrieve a specific agent\'s systemPrompt',
        ),
        name: z.string().optional().describe('Agent name (required for action=get, e.g. "architect", "security-reviewer")'),
      },
      (params) => {
        const result = handleAgentPassthrough(roleAgentRegistry, {
          action: params.action,
          name: params.name,
        });
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_benchmark',
      'Run Gestalt pipeline benchmarks in passthrough mode. Actions: start (begin a scenario), respond (submit LLM response), status (check progress). No API key required — caller acts as the LLM.',
      {
        action: z.enum(['start', 'respond', 'status']).describe(
          'start: begin benchmark scenario, respond: submit LLM response for current step, status: check benchmark progress',
        ),
        scenario: z.string().optional().describe('Scenario name for start: auth-system, dashboard, api-gateway'),
        benchmarkSessionId: z.string().optional().describe('Benchmark session ID (required for respond/status)'),
        response: z.string().optional().describe('JSON response from the caller LLM (required for respond)'),
        usage: z.object({
          inputTokens: z.number(),
          outputTokens: z.number(),
        }).optional().describe('Token usage from the caller LLM call (optional, for metrics)'),
      },
      (params) => {
        const input = benchmarkInputSchema.parse(params);
        const result = handleBenchmarkPassthrough(input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_status',
      'Check the status of interview and execute sessions.',
      {
        sessionId: z.string().optional().describe('Specific session ID to check (omit for all sessions)'),
        sessionType: z.enum(['interview', 'execute', 'all']).optional().default('all')
          .describe('Filter by session type (default: all)'),
      },
      (params) => {
        const input = statusInputSchema.parse(params);
        const result = handleStatusPassthrough(ptEngine, ptExecuteEngine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_code_graph',
      'Build and query the code knowledge graph for a repository. Actions: build (index codebase), blast_radius (find impacted files from changes), query (graph traversal), stats (show DB stats), db_exists (check if graph DB exists).',
      {
        action: z.enum(['build', 'blast_radius', 'query', 'stats', 'db_exists']).describe(
          'build: index codebase into graph DB, blast_radius: find files impacted by changes, query: traverse graph, stats: show stats, db_exists: check if DB exists',
        ),
        repoRoot: z.string().describe('Absolute path to the repository root'),
        include: z.array(z.string()).optional().describe('Glob patterns to include (default: **/*)'),
        exclude: z.array(z.string()).optional().describe('Glob patterns to exclude'),
        mode: z.enum(['full', 'incremental']).optional().describe('Build mode: full (default) or incremental (hash-based skip)'),
        changedFiles: z.array(z.string()).optional().describe('Changed file paths (auto-detected from git diff HEAD~1 if omitted)'),
        base: z.string().optional().describe('Git base ref for diff detection (default: HEAD~1)'),
        maxDepth: z.number().optional().describe('BFS traversal depth for blast_radius (default: 2)'),
        pattern: z.enum(['callers_of', 'callees_of', 'tests_for', 'imports_of']).optional()
          .describe('Query pattern (required for query action)'),
        target: z.string().optional().describe('Target function or file path (required for query action)'),
      },
      async (params) => {
        const input = codeGraphInputSchema.parse(params);
        const result = await handleCodeGraphPassthrough(input);
        return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
      },
    );

    server.tool(
      'ges_graph_visualize',
      'Start a local HTTP server that renders an interactive D3.js force-directed graph visualization of the code knowledge graph. Opens the browser automatically. Requires an existing or auto-buildable code-graph.db.',
      {
        repoRoot: z.string().describe('Absolute path to the repository root'),
        port: z.number().optional().describe('Preferred server port (default: 7891, auto-increments on conflict)'),
      },
      async (params) => {
        const input = graphVisualizeInputSchema.parse(params);
        const result = await handleGraphVisualizePassthrough(input);
        return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
      },
    );
  } else {
    // ─── Normal mode: direct LLM calls ──────────────────────────
    const llm = new AnthropicAdapter(config.llm.apiKey, config.llm.model);
    const engine = new InterviewEngine(llm, eventStore);
    const specGenerator = new SpecGenerator(llm, eventStore);

    server.tool(
      'ges_interview',
      'Conduct a Gestalt-driven interview to clarify project requirements. Actions: start, respond, score, complete.',
      {
        action: z.enum(['start', 'respond', 'score', 'complete']).describe(
          'start: begin interview, respond: answer a question, score: check resolution, complete: finish interview',
        ),
        topic: z.string().optional().describe('Topic for the interview (required for start)'),
        sessionId: z.string().optional().describe('Session ID (required for respond/score/complete)'),
        response: z.string().optional().describe('User response to the current question (required for respond)'),
        cwd: z.string().optional().describe('Working directory for brownfield detection'),
        record: z.boolean().optional().describe('Generate a GIF recording of the interview session on complete'),
      },
      async (params) => {
        const input = interviewInputSchema.parse(params);
        const result = await handleInterview(engine, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_generate_spec',
      'Generate a Spec specification from a completed interview session.',
      {
        sessionId: z.string().describe('The interview session ID'),
        force: z.boolean().optional().default(false).describe(
          'Force generation even if resolution threshold is not met',
        ),
      },
      async (params) => {
        const input = specInputSchema.parse(params);
        const result = await handleSpec(engine, specGenerator, input);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );

    server.tool(
      'ges_status',
      'Check the status of interview and execute sessions.',
      {
        sessionId: z.string().optional().describe('Specific session ID to check (omit for all sessions)'),
        sessionType: z.enum(['interview', 'execute', 'all']).optional().default('all')
          .describe('Filter by session type (default: all)'),
      },
      (params) => {
        const input = statusInputSchema.parse(params);
        const result = handleStatus(engine, input, eventStore);
        return { content: [{ type: 'text' as const, text: result }] };
      },
    );
  }

  return { server, eventStore, skillRegistry, agentRegistry };
}

// Status handler for passthrough mode — uses PassthroughEngine + PassthroughExecuteEngine
function handleStatusPassthrough(
  engine: PassthroughEngine,
  executeEngine: PassthroughExecuteEngine,
  input: { sessionId?: string; sessionType?: 'interview' | 'execute' | 'all' },
): string {
  const updateResult = getCachedUpdateResult();
  const versionInfo = {
    current: getVersion(),
    latest: updateResult?.latestVersion ?? null,
    updateAvailable: updateResult?.updateAvailable ?? false,
  };
  const sessionType = input.sessionType ?? 'all';

  try {
    if (input.sessionId) {
      // Try interview first, then execute
      try {
        const session = engine.getSession(input.sessionId);
        return JSON.stringify({
          versionInfo,
          type: 'interview',
          session: {
            sessionId: session.sessionId,
            topic: session.topic,
            status: session.status,
            projectType: session.projectType,
            totalRounds: session.rounds.length,
            answeredRounds: session.rounds.filter((r) => r.userResponse).length,
            resolutionScore: session.resolutionScore
              ? {
                  overall: session.resolutionScore.overall.toFixed(2),
                  isReady: session.resolutionScore.isReady,
                }
              : null,
            createdAt: session.createdAt,
            updatedAt: session.updatedAt,
          },
        }, null, 2);
      } catch {
        // Not found in interview, try execute
        const session = executeEngine.getSession(input.sessionId);
        return JSON.stringify({
          versionInfo,
          type: 'execute',
          session: formatExecuteSession(session),
        }, null, 2);
      }
    }

    // List mode
    const interviewSessions = (sessionType === 'interview' || sessionType === 'all')
      ? engine.listSessions().map((s) => ({
          sessionId: s.sessionId,
          topic: s.topic,
          status: s.status,
          projectType: s.projectType,
          totalRounds: s.rounds.length,
          resolutionScore: s.resolutionScore?.overall.toFixed(2) ?? 'N/A',
          createdAt: s.createdAt,
        }))
      : [];

    const executeSessions = (sessionType === 'execute' || sessionType === 'all')
      ? executeEngine.listSessions().map((s) => formatExecuteSessionSummary(s))
      : [];

    return JSON.stringify({
      versionInfo,
      interviewSessions,
      executeSessions,
      total: { interview: interviewSessions.length, execute: executeSessions.length },
    }, null, 2);
  } catch (e) {
    return JSON.stringify({
      error: e instanceof Error ? e.message : String(e),
    }, null, 2);
  }
}

function formatExecuteSessionSummary(session: import('../core/types.js').ExecuteSession) {
  const totalTasks = session.executionPlan?.atomicTasks.length ?? 0;
  const completedTasks = session.taskResults.filter((t) => t.status === 'completed').length;
  return {
    sessionId: session.sessionId,
    specId: session.specId,
    status: session.status,
    goal: session.spec.goal,
    currentStep: session.currentStep,
    hasPlan: !!session.executionPlan,
    taskProgress: totalTasks > 0 ? `${completedTasks}/${totalTasks}` : null,
    evaluationScore: session.evaluationResult?.overallScore ?? null,
    goalAlignment: session.evaluationResult?.goalAlignment ?? null,
    evaluateStage: session.evaluateStage ?? null,
    evolveStage: session.evolveStage ?? null,
    currentGeneration: session.currentGeneration,
    lateralPersonas: session.lateralTriedPersonas.length > 0 ? session.lateralTriedPersonas : null,
    terminationReason: session.terminationReason ?? null,
    createdAt: session.createdAt,
  };
}

function formatExecuteSession(session: import('../core/types.js').ExecuteSession) {
  const totalTasks = session.executionPlan?.atomicTasks.length ?? 0;
  const completedTasks = session.taskResults.filter((t) => t.status === 'completed').length;
  const failedTasks = session.taskResults.filter((t) => t.status === 'failed').length;
  const pendingTasks = totalTasks - completedTasks - failedTasks;
  const totalACs = session.spec.acceptanceCriteria.length;
  const satisfiedACs = session.evaluationResult
    ? session.evaluationResult.verifications.filter((v) => v.satisfied).length
    : 0;

  return {
    sessionId: session.sessionId,
    specId: session.specId,
    status: session.status,
    goal: session.spec.goal,
    currentStep: session.currentStep,
    stepsCompleted: session.planningSteps.map((s) => s.principle),
    hasPlan: !!session.executionPlan,
    taskProgress: { total: totalTasks, completed: completedTasks, failed: failedTasks, pending: pendingTasks },
    satisfiedACs: `${satisfiedACs}/${totalACs}`,
    evaluateStage: session.evaluateStage ?? null,
    hasEvaluation: !!session.evaluationResult,
    evaluationScore: session.evaluationResult?.overallScore ?? null,
    goalAlignment: session.evaluationResult?.goalAlignment ?? null,
    driftAlerts: session.driftHistory.filter((d) => d.thresholdExceeded).length,
    evolution: session.evolutionHistory.length > 0 ? {
      scoreProgression: session.evolutionHistory.map((gen) => ({
        generation: gen.generation,
        score: gen.evaluationScore,
        goalAlignment: gen.goalAlignment,
        fieldsChanged: Object.keys(gen.delta).filter((k) => {
          const val = gen.delta[k as keyof typeof gen.delta];
          return Array.isArray(val) ? val.length > 0 : val !== undefined;
        }),
      })),
      summary: summarizeEvolution(session),
    } : null,
    evolveStage: session.evolveStage ?? null,
    currentGeneration: session.currentGeneration,
    terminationReason: session.terminationReason ?? null,
    lateral: session.lateralTriedPersonas.length > 0 ? {
      triedPersonas: session.lateralTriedPersonas,
      totalAttempts: session.lateralAttempts,
      currentPersona: session.lateralCurrentPersona ?? null,
      currentPattern: session.lateralCurrentPattern ?? null,
    } : null,
    roleAgent: session.roleMatches ? {
      matchedAgents: session.roleMatches.map((m) => m.agentName),
      hasConsensus: !!session.roleConsensus,
    } : null,
    createdAt: session.createdAt,
    updatedAt: session.updatedAt,
  };
}

function summarizeEvolution(session: import('../core/types.js').ExecuteSession): string {
  const history = session.evolutionHistory;
  if (history.length === 0) return 'No evolution';
  const first = history[0]!;
  const last = history[history.length - 1]!;
  const scoreDelta = (last.evaluationScore - first.evaluationScore).toFixed(2);
  const sign = Number(scoreDelta) >= 0 ? '+' : '';
  const parts = [
    `${history.length} generation${history.length > 1 ? 's' : ''}`,
    `Score: ${first.evaluationScore.toFixed(2)} → ${last.evaluationScore.toFixed(2)} (${sign}${scoreDelta})`,
    `Goal: ${first.goalAlignment.toFixed(2)} → ${last.goalAlignment.toFixed(2)}`,
  ];
  if (session.terminationReason) {
    parts.push(`Terminated: ${session.terminationReason}`);
  }
  return parts.join(' | ');
}

export async function startMcpServer(configOverrides?: Partial<GestaltConfig>) {
  const config = loadConfig(configOverrides);
  const isPassthrough = !config.llm.apiKey;
  const { server, skillRegistry, agentRegistry } = await createMcpServer(configOverrides);

  skillRegistry.startWatching();
  agentRegistry.startWatching();

  const transport = new StdioServerTransport();
  await server.connect(transport);

  log(`MCP server started on stdio${isPassthrough ? ' (passthrough mode)' : ''}`);

  checkForUpdates().then((result) => {
    if (result?.updateAvailable) {
      log(`Update available: ${result.currentVersion} → ${result.latestVersion}`);
      log(`Run: npx -y @tienne/gestalt@latest`);
    }
  }).catch(() => {});

  process.on('SIGINT', async () => {
    await skillRegistry.stopWatching();
    await agentRegistry.stopWatching();
    await server.close();
    process.exit(0);
  });
}
