export enum EventType {
  INTERVIEW_SESSION_STARTED = 'interview.session.started',
  INTERVIEW_QUESTION_ASKED = 'interview.question.asked',
  INTERVIEW_RESPONSE_RECORDED = 'interview.response.recorded',
  INTERVIEW_AMBIGUITY_SCORED = 'interview.ambiguity.scored',
  INTERVIEW_SESSION_COMPLETED = 'interview.session.completed',
  GESTALT_PRINCIPLE_APPLIED = 'gestalt.principle.applied',
  SEED_SPEC_GENERATED = 'seed.spec.generated',
  BROWNFIELD_DETECTED = 'brownfield.detected',
  EXECUTE_SESSION_STARTED = 'execute.session.started',
  EXECUTE_PLANNING_STEP_COMPLETED = 'execute.planning.step.completed',
  EXECUTE_PLAN_VALIDATED = 'execute.plan.validated',
  EXECUTE_PLAN_COMPLETED = 'execute.plan.completed',
  EXECUTE_SESSION_FAILED = 'execute.session.failed',
  EXECUTE_EXECUTION_STARTED = 'execute.execution.started',
  EXECUTE_TASK_COMPLETED = 'execute.task.completed',
  EXECUTE_EVALUATION_COMPLETED = 'execute.evaluation.completed',
  EXECUTE_SESSION_COMPLETED = 'execute.session.completed',
  EVALUATE_STRUCTURAL_STARTED = 'evaluate.structural.started',
  EVALUATE_STRUCTURAL_COMPLETED = 'evaluate.structural.completed',
  EVALUATE_CONTEXTUAL_STARTED = 'evaluate.contextual.started',
  EVALUATE_CONTEXTUAL_COMPLETED = 'evaluate.contextual.completed',
  EVALUATE_SHORT_CIRCUITED = 'evaluate.short.circuited',
  EXECUTE_DRIFT_MEASURED = 'execute.drift.measured',
  EXECUTE_DRIFT_RETROSPECTIVE = 'execute.drift.retrospective',
}
