export enum EventType {
  INTERVIEW_SESSION_STARTED = 'interview.session.started',
  INTERVIEW_QUESTION_ASKED = 'interview.question.asked',
  INTERVIEW_RESPONSE_RECORDED = 'interview.response.recorded',
  INTERVIEW_AMBIGUITY_SCORED = 'interview.ambiguity.scored',
  INTERVIEW_SESSION_COMPLETED = 'interview.session.completed',
  GESTALT_PRINCIPLE_APPLIED = 'gestalt.principle.applied',
  SEED_SPEC_GENERATED = 'seed.spec.generated',
  BROWNFIELD_DETECTED = 'brownfield.detected',
  EXECUTE_SESSION_STARTED = 'execute.session.started',
  EXECUTE_PLANNING_STEP_COMPLETED = 'execute.planning.step.completed',
  EXECUTE_PLAN_VALIDATED = 'execute.plan.validated',
  EXECUTE_PLAN_COMPLETED = 'execute.plan.completed',
  EXECUTE_SESSION_FAILED = 'execute.session.failed',
}
