import type { VocabularyPack } from './types.js';

/**
 * 웹 제품. 화면에서 API, 서버, DB로 가는 요청 길과 그 서빙 인프라, 배포 경로를 그린다.
 * 색은 밝은 화면이 600 톤, 어두운 화면이 400 톤이다. 같은 색상환 자리라 테마를 바꿔도 같은 종류로 읽힌다.
 * 열 순위는 두 뷰의 kind가 겹치지 않아 표 하나로 둘 다 덮는다. 뷰①은 service→feature→screen→gateway→endpoint→module→클라이언트→테이블,
 * 뷰②는 workflow→build→artifact→배포처 순서로 왼쪽부터 놓인다. 인프라는 배포 경로에서 산출물이 떨어지는 버킷부터 CDN, 도메인 순으로
 * 오른쪽에 붙는다. 요청 방향(도메인→CDN→버킷)과 반대라 그 선은 거꾸로 그린다
 */
export const WEB_PRODUCT_PACK = {
  id: 'web-product',
  title: '웹 제품',
  description: '화면, API, 서버, 저장소와 서빙 인프라, 배포 경로',
  drilldown: 'web-product',
  matchers: ['http-endpoint'],
  nodeKinds: {
    // service는 웹과 앱을 함께 담으므로 "서비스"로 쓰고 어느 쪽인지는 플랫폼 칩이 따로 알린다
    service: {
      renderClass: 'service',
      short: '서비스',
      text: '서비스',
      about:
        '사용자가 쓰는 제품 하나예요. 웹과 앱을 함께 담고 그 아래에 앱, 기능 영역, 화면이 들어가요.',
      color: { light: '#2563eb', dark: '#60a5fa' },
      icon: '<path d="M12 3.5l8.5 4.3L12 12 3.5 7.8z"/><path d="M3.5 12.2L12 16.5l8.5-4.3"/><path d="M3.5 16.4L12 20.7l8.5-4.3"/>',
      lane: 'screen',
      rank: 0,
    },
    micro_app: {
      renderClass: 'client',
      // 호스트 카드는 렌더러가 '호스트'로 바꿔 단다. 두 글자 폭이 같아야 카드 폭 계산이 하나로 맞는다
      short: '리모트',
      text: '마이크로 프론트엔드 앱',
      about:
        '따로 빌드하고 배포하는 프론트엔드 앱이에요. 호스트 앱이 리모트 앱을 실행 중에 불러와 한 서비스로 보여줘요.',
      color: { light: '#0369a1', dark: '#7dd3fc' },
      icon: '<rect x="3.5" y="3.5" width="7" height="7" rx="1.5"/><rect x="13.5" y="3.5" width="7" height="7" rx="1.5"/><rect x="3.5" y="13.5" width="7" height="7" rx="1.5"/><path d="M17 13.5v7M13.5 17h7"/>',
      lane: 'screen',
      rank: 0,
      // Module Federation 같은 마이크로 프론트엔드의 호스트나 리모트다. 서비스가 그 묶음이고 기능 영역과 화면은 페이지 코드가 있는 앱 밑에 둔다
      parents: ['service'],
    },
    feature: {
      renderClass: 'client',
      short: '기능 영역',
      text: '기능 영역',
      about: '화면 여럿을 업무 단위로 묶은 영역이에요.',
      color: { light: '#0891b2', dark: '#22d3ee' },
      icon: '<path d="M3.5 7.5a2 2 0 0 1 2-2h3.6l2 2.2h7.4a2 2 0 0 1 2 2v7.8a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2z"/>',
      lane: 'screen',
      rank: 0,
      parents: ['micro_app', 'service'],
    },
    screen: {
      renderClass: 'client',
      short: '화면',
      text: '화면',
      about: '사용자가 보는 페이지 하나예요.',
      color: { light: '#4f46e5', dark: '#818cf8' },
      icon: '<rect x="3" y="4.5" width="18" height="15" rx="2.5"/><path d="M3 9h18"/><path d="M6.5 6.8h.01M9 6.8h.01"/>',
      lane: 'screen',
      rank: 0,
      parents: ['feature', 'micro_app', 'service'],
    },
    gateway: {
      renderClass: 'gateway',
      short: '게이트웨이',
      text: '게이트웨이',
      about: '요청을 먼저 받아 뒤쪽 API나 서버로 넘기는 관문이에요.',
      color: { light: '#475569', dark: '#94a3b8' },
      icon: '<path d="M12 3l7.5 3v5.5c0 4.4-3.1 8-7.5 9.5-4.4-1.5-7.5-5.1-7.5-9.5V6z"/>',
      lane: 'gateway',
      rank: 1,
    },
    endpoint: {
      renderClass: 'service',
      short: 'API',
      text: 'API',
      about: '화면이나 다른 서버가 부르는 서버 주소예요. 메서드와 경로로 구분해요.',
      color: { light: '#059669', dark: '#34d399' },
      icon: '<path d="M8.5 7.5L4 12l4.5 4.5M15.5 7.5L20 12l-4.5 4.5M13.5 5.5l-3 13"/>',
      lane: 'endpoint',
      rank: 2,
      // MCP 도구만 받는다. 스킬 없이 클라이언트가 바로 부르는 도구가 어느 서버 패키지 것인지 적는 자리다
      parents: ['service'],
    },
    app_module: {
      renderClass: 'service',
      short: '서버',
      text: '서버',
      about: '요청을 실제로 처리하는 서버 코드 묶음이에요.',
      color: { light: '#7c3aed', dark: '#a78bfa' },
      icon: '<rect x="3.5" y="4" width="17" height="7" rx="1.8"/><rect x="3.5" y="13" width="17" height="7" rx="1.8"/><path d="M7 7.5h.01M7 16.5h.01M11 7.5h6M11 16.5h6"/>',
      lane: 'app_module',
      rank: 3,
    },
    external_service: {
      renderClass: 'external',
      short: '클라이언트',
      text: '호출 클라이언트',
      about: '서버가 다른 서비스를 부를 때 쓰는 호출 코드예요.',
      color: { light: '#d97706', dark: '#fbbf24' },
      icon: '<path d="M9 3v4.5M15 3v4.5"/><path d="M6.5 7.5h11v3.5a5.5 5.5 0 0 1-11 0z"/><path d="M12 16.5V21"/>',
      lane: 'external_service',
      rank: 4,
    },
    db_table: {
      renderClass: 'store',
      short: 'DB',
      text: '테이블',
      about: '서버가 읽고 쓰는 DB 테이블이에요.',
      color: { light: '#dc2626', dark: '#f87171' },
      icon: '<ellipse cx="12" cy="5.5" rx="7.5" ry="2.8"/><path d="M4.5 5.5v13c0 1.5 3.4 2.8 7.5 2.8s7.5-1.3 7.5-2.8v-13"/><path d="M4.5 12c0 1.5 3.4 2.8 7.5 2.8s7.5-1.3 7.5-2.8"/>',
      lane: 'db_table',
      rank: 5,
      parents: ['datastore'],
    },
    datastore: {
      renderClass: 'store',
      short: '저장소',
      text: '저장소 클러스터',
      about: '테이블이 들어 있는 DB나 캐시 클러스터예요.',
      color: { light: '#be123c', dark: '#fb7185' },
      icon: '<ellipse cx="12" cy="5" rx="7.5" ry="2.5"/><path d="M4.5 5v4.5c0 1.4 3.4 2.5 7.5 2.5s7.5-1.1 7.5-2.5V5"/><path d="M4.5 9.5V14c0 1.4 3.4 2.5 7.5 2.5s7.5-1.1 7.5-2.5V9.5"/><path d="M4.5 14v4.5c0 1.4 3.4 2.5 7.5 2.5s7.5-1.1 7.5-2.5V14"/>',
      // 클러스터는 테이블과 같은 rank라 같은 레인에 둔다
      lane: 'db_table',
      rank: 5,
    },
    workflow: {
      renderClass: 'step',
      short: '트리거',
      text: '워크플로',
      about: '푸시나 태그가 생기면 도는 CI 워크플로예요. 배포 경로가 여기서 시작해요.',
      color: { light: '#0284c7', dark: '#38bdf8' },
      icon: '<path d="M13 2.5L4.5 13.5H11l-1 8 8.5-11H12z"/>',
      lane: 'workflow',
      rank: 0,
    },
    build: {
      renderClass: 'step',
      short: '빌드',
      text: '빌드',
      about: '소스를 빌드하는 단계예요.',
      color: { light: '#0d9488', dark: '#2dd4bf' },
      icon: '<path d="M14.5 6.2a4 4 0 0 0-5.3 5.3L3.5 17.2l3.3 3.3 5.7-5.7a4 4 0 0 0 5.3-5.3l-2.6 2.6-2.5-.2-.2-2.5z"/>',
      lane: 'build',
      rank: 1,
    },
    artifact: {
      renderClass: 'document',
      short: '산출물',
      text: '산출물',
      about: '빌드가 내놓은 이미지나 번들이에요.',
      color: { light: '#9333ea', dark: '#c084fc' },
      icon: '<path d="M12 2.8l8.5 4.7v9L12 21.2l-8.5-4.7v-9z"/><path d="M3.5 7.5L12 12l8.5-4.5M12 12v9.2"/>',
      lane: 'artifact',
      rank: 2,
    },
    deploy_target: {
      renderClass: 'infra',
      short: '배포 대상',
      text: '배포 대상',
      about: '산출물이 올라가 실제로 도는 곳이에요.',
      color: { light: '#ea580c', dark: '#fb923c' },
      icon: '<path d="M7 18.5a4.5 4.5 0 0 1-.7-8.95A6 6 0 0 1 17.8 8.6a4.95 4.95 0 0 1-.8 9.9z"/><path d="M12 11v5M9.8 13.2L12 11l2.2 2.2"/>',
      lane: 'deploy_target',
      rank: 3,
    },
    domain: {
      renderClass: 'infra',
      short: '도메인',
      text: '도메인',
      about: '사용자가 접속하는 주소예요.',
      color: { light: '#db2777', dark: '#f472b6' },
      icon: '<path d="M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1"/><path d="M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1"/>',
      lane: 'domain',
      rank: 6,
    },
    cdn: {
      renderClass: 'infra',
      short: 'CDN',
      text: 'CDN 배포',
      about: '도메인으로 온 요청을 받아 원본의 파일을 내주는 CDN이에요.',
      color: { light: '#4338ca', dark: '#a5b4fc' },
      icon: '<circle cx="12" cy="12" r="8.5"/><path d="M3.5 12h17M12 3.5c2.5 2.6 3.5 5.4 3.5 8.5s-1 5.9-3.5 8.5c-2.5-2.6-3.5-5.4-3.5-8.5s1-5.9 3.5-8.5z"/>',
      lane: 'cdn',
      rank: 5,
    },
    bucket: {
      renderClass: 'store',
      short: '버킷',
      text: '스토리지 버킷',
      about: '빌드한 정적 파일을 담아두는 저장소예요.',
      color: { light: '#16a34a', dark: '#4ade80' },
      icon: '<ellipse cx="12" cy="6.5" rx="8" ry="2.5"/><path d="M4 6.5l2 13a2 2 0 0 0 2 1.5h8a2 2 0 0 0 2-1.5l2-13"/>',
      lane: 'bucket',
      rank: 4,
    },
    cloud_account: {
      renderClass: 'infra',
      short: '계정',
      text: '클라우드 계정',
      about: '인프라가 속한 클라우드 계정이에요.',
      color: { light: '#57534e', dark: '#a8a29e' },
      icon: '<rect x="3.5" y="5" width="17" height="14" rx="2.5"/><circle cx="9" cy="11" r="2.2"/><path d="M5.8 16.2a3.5 3.5 0 0 1 6.4 0M14.5 10h3M14.5 13.5h3"/>',
      lane: 'cloud_account',
      rank: 7,
    },
  },
  lanes: {
    service: { title: '서비스', about: '제품 단위인 서비스가 서는 칸이에요.', stacked: true },
    host: {
      title: '호스트',
      about: '사용자가 처음 받는 호스트 앱이 서는 칸이에요.',
      stacked: true,
    },
    remote: {
      title: '리모트',
      about: '호스트 앱이 실행 중에 불러오는 리모트 앱이 서는 칸이에요.',
      stacked: true,
    },
    unit: { title: '기능 영역', about: '화면을 묶은 기능 영역이 서는 칸이에요.', stacked: true },
    screen: { title: '화면', about: '사용자가 보는 화면이 서는 칸이에요.', stacked: true },
    gateway: { title: '게이트웨이', about: '요청이 먼저 지나는 게이트웨이가 서는 칸이에요.' },
    endpoint: { title: 'API', about: '화면이나 다른 서버가 부르는 API가 서는 칸이에요.' },
    app_module: { title: '서버', about: '요청을 처리하는 서버 코드가 서는 칸이에요.' },
    external_service: {
      title: '클라이언트',
      about: '서버가 다른 서비스를 부를 때 쓰는 호출 클라이언트가 서는 칸이에요.',
    },
    external: { title: '외부 서비스', about: '우리가 운영하지 않는 바깥 서비스가 서는 칸이에요.' },
    db_table: { title: 'DB', about: 'DB 테이블과 저장소 클러스터가 서는 칸이에요.' },
    workflow: { title: '트리거', about: '배포를 시작하는 워크플로가 서는 칸이에요.' },
    build: { title: '빌드', about: '빌드 단계가 서는 칸이에요.' },
    artifact: { title: '산출물', about: '빌드가 내놓은 산출물이 서는 칸이에요.' },
    deploy_target: { title: '배포 대상', about: '산출물이 올라가 도는 배포 대상이 서는 칸이에요.' },
    domain: { title: '도메인', about: '사용자가 접속하는 도메인이 서는 칸이에요.' },
    cdn: { title: 'CDN', about: '도메인으로 온 요청을 받는 CDN이 서는 칸이에요.' },
    bucket: { title: '버킷', about: '정적 파일을 담은 버킷이 서는 칸이에요.' },
    cloud_account: {
      title: '클라우드 계정',
      about: '인프라가 속한 클라우드 계정이 서는 칸이에요.',
    },
  },
  edgeKinds: {
    calls: {
      text: '호출',
      about:
        '앞쪽이 뒤쪽을 부르는 연결이에요. 화면의 API 호출, 클라이언트의 게이트웨이 호출, 스킬의 MCP 도구 호출이 여기 들어가요.',
    },
    handles: {
      text: '처리',
      about: 'API나 MCP 도구로 들어온 요청을 서버 코드가 받아 처리하는 연결이에요.',
    },
    uses: {
      text: '사용',
      about: '서버가 호출 클라이언트나 같은 프로세스의 다른 모듈을 쓰는 연결이에요.',
    },
    reads_writes: {
      text: '읽기와 쓰기',
      about: '서버가 테이블이나 저장소를 읽고 쓰는 연결이에요.',
    },
    routes: {
      text: '전달',
      about: '게이트웨이가 받은 요청을 다음 게이트웨이나 API, 서버로 넘기는 연결이에요.',
    },
    navigates: { text: '화면 이동', about: '한 화면에서 다른 화면으로 넘어가는 연결이에요.' },
    triggers: { text: '실행', about: '워크플로가 빌드를 돌리는 연결이에요.' },
    builds: { text: '빌드', about: '빌드가 산출물을 만드는 연결이에요.' },
    produces: {
      text: '생성',
      about: '빌드가 산출물을 내보내는 연결이에요. 이미지 푸시나 업로드가 여기 들어가요.',
    },
    deploys_to: { text: '배포', about: '산출물을 배포 대상이나 버킷에 올리는 연결이에요.' },
    resolves_to: {
      text: '도메인 연결',
      about: '도메인이 CDN이나 배포 대상을 가리키는 연결이에요.',
      backward: true,
    },
    origin: {
      text: '원본',
      about: 'CDN이 파일을 가져오는 원본을 가리키는 연결이에요.',
      backward: true,
    },
    serves: { text: '서빙', about: '버킷이나 배포 대상이 그 앱을 사용자에게 내주는 연결이에요.' },
    loads: {
      text: '런타임 로드',
      about:
        '실행 중에 다른 것을 읽어 들이는 연결이에요. 호스트 앱이 리모트 앱을, AI 클라이언트가 플러그인을, 레지스트리가 에이전트를 읽어요.',
    },
  },
} as const satisfies VocabularyPack;
